version: "3.7"
services:
  mysqldb:
    image: mysql:8
    environment:
      - MYSQL_USER=commit_app
      - MYSQL_PASSWORD=12345YYyy
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb
  commit-viewer:
    build: .
    ports: 
      - 8080:8080
    depends_on:
      - mysqldb

    
      